### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by saleheenkhan** [allourideas/allourideas.org#57]
Hi,
i am trying to install this app v4.0.0 but when i ran the db migrate command i am getting some errors

![image](https://user-images.githubusercontent.com/8937927/40270329-f75f4d0a-5bac-11e8-9765-b8ea7fece4dc.png)

I tried following versions of ROR, but not working

Ruby 2.4.4
Ruby 2.3.7
Ruby 2.2.10
Ruby 2.1.10
Ruby 2.0.0

& Can you let me know which version of ROR is Compatible for this app?

Looking Forward to Hear from you soon

Thanks

**Comment by lukebaker** [comment]
@saleheenkhan per the [installation documentation](https://github.com/allourideas/allourideas.org/wiki/Installing), this project is compatible with Ruby 1.9.3.
