### ISSUE TITLE
Secure the website using https

### ISSUE THREAD

**Issue by afomi** [allourideas/allourideas.org#67]
# Background

The website currently offers a login feature, which requires a password.
However, the site is delivered via http, which is less secure than https.

# Acceptance Criteria

Visiting allourideas.org renders using `https` protocol, instead of `http`.

**Comment by lukebaker** [comment]
@afomi, thanks for this report. We had soft-launched https but weren't redirecting from http to https. I've now updated the configuration so that all http requests get redirected to https.
