### ISSUE TITLE
allourideas.org is down

### ISSUE THREAD

**Issue by wu-lee** [allourideas/allourideas.org#74]
Hello,

Came to check out what allourideas.org is about, found the site was down. (Checked the site on archive.org, found links here.)

Domain resolves, title appears, but the page never appears, sits with the progress indicator spinning.

Tx

**Comment by lukebaker** [comment]
It's working for me and [this site indicates that it is working elsewhere](https://downforeveryoneorjustme.com/allourideas.org).
