### ISSUE TITLE
Widget shows cookies blocked message

### ISSUE THREAD

**Issue by lukebaker** [allourideas/allourideas.org#76]
We have some code in place that attempts to detect if cookies are blocked. However, it's possible that the detection code is showing false positives because _it's_ attempts to read / write cookies are blocked but that the site will operate successfully despite that. Without researching too much, I believe some browsers like Safari may have stricter cookie restrictions in place for third-party JavaScript code than server responses that set cookies. I believe we use the former for detection and the latter for proper functioning of the site.

**Comment by lukebaker** [comment]
My research indicates that this may be due to recent SameSite changes in browsers. I believe we need to be sending `SameSite=None; Secure` with our cookies. Unfortunately, the version of Rails that we're running doesn't support those options natively, so we'll need to do further research to determine how we can implement these changes.

**Comment by msalganik** [comment]
OK, thanks Luke.

A few questions:
1) What problem is caused by this issue?  What user experience is harmed and how?
2) How big a job would it be to upgrade to the newest version of Rails?  My memory is that this is a big job, but I don't remember exactly.

Thanks.

**Comment by lukebaker** [comment]
> What problem is caused by this issue? What user experience is harmed and how?

When people embed the wiki survey via the widget or the full All Our Ideas site, most users will see an error like this one:
![Screenshot from 2020-10-26 09-50-01](https://user-images.githubusercontent.com/84748/97180719-c98a6b80-1770-11eb-9d50-a33097989618.png)

> How big a job would it be to upgrade to the newest version of Rails?  My memory is that this is a big job, but I don't remember exactly.

Yes, that would be a substantial amount of work. I'm not sure exactly how much time that'd take. If we want to investigate that a bit more, it might be good to spend a couple days trying to get a good overview of the work involved. For this particular issue, we _may_ be able to find a solution that doesn't involve upgrading Rails, but it'd definitely be a bit of a hack. I stopped where I did because I didn't think that research would fit into the 1 hour time block we had allocated for this issue.

**Comment by lukebaker** [comment]
@msalganik I'm unable to figure out any way to get Safari 14 to allow iframe cookies like AOI needs without having the user modify their browser settings, which I don't think is a good idea. It looks like both Chrome and Firefox have ways of achieving this, at least for now. I'm not sure if Chrome and Firefox have plans for further changes that will put them more in line with how Safari is doing things.

There may be options to use localStorage and JavaScript to do the work that cookies are doing for us, but I think that would be a fairly significant undertaking. Unfortunately, I wonder if we should leave things mostly as-is but change the message to remove "or allow third-party cookies in your browser". Essentially this means the widget is no longer supported as most users will be seeing this message. However, they can always visit allourideas.org to vote. What do you think of that plan?

**Comment by msalganik** [comment]
Thanks Luke.  I totally understand why Safari is making these changes, and I heard in that talk that Firefox is joining.  Chrome is a different story.

I don't think we should undertake a big new job to make the widget work.  So, I think the answer is to stop supporting the widget.  It had a nice, long run.

Eventually, maybe we can find a user who wants to widget who can pay for the improvements.

Next steps:
- I agree with your plan to update the message to remove "or allow third-party cookies in your browser".
- I think we should make a blog post announcing the change and then linking to the new blog post from the old posts that talk about the widget.  Can you draft a few sentences explaining the technical reason why we no longer supporting the widget?  I'll take care of the rest of the blog stuff, but I want to have a a clear and correct explanation of why we are depreciating this feature.
- Can you create an issue that describes the work that might be done to solve this problem?  Then we can direct people who want this feature to that issue?

**Comment by lukebaker** [comment]
> I agree with your plan to update the message to remove "or allow third-party cookies in your browser".

This is all set as of #81.

> I think we should make a blog post announcing the change and then linking to the new blog post from the old posts that talk about the widget. Can you draft a few sentences explaining the technical reason why we no longer supporting the widget? I'll take care of the rest of the blog stuff, but I want to have a a clear and correct explanation of why we are depreciating this feature.

How about this:

Due to browser changes in the past years to improve users' security, third-party cookies are now blocked by default in some browsers and others have added new standards that require changes to applications for continued working of third-party cookies.

Content within an iframe is considered third-party, which is the mechanism that the All Our Ideas site has used for years with great success. However, due to the restrictions on third-party cookies the widget no longer works in the majority of browsers.

> Can you create an issue that describes the work that might be done to solve this problem?  Then we can direct people who want this feature to that issue?

Yep, I've created that here: https://github.com/allourideas/allourideas.org/issues/82

**Comment by msalganik** [comment]
Thanks Luke.
