### ISSUE TITLE
Widget does not work due to lack of access to third-party cookies

### ISSUE THREAD

**Issue by lukebaker** [allourideas/allourideas.org#82]
Due to browser changes in the past years to improve users' security, third-party cookies are now [blocked by default in some browsers](https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/) and others have added [new standards](https://web.dev/samesite-cookies-explained/) that require changes to applications for continued working of third-party cookies.

Content within an iframe is considered third-party and this is the typical way to embed functionality on a site that's powered by another site. This is the mechanism that the All Our Ideas site has used for years with great success. However, due to the restrictions on third-party cookies the widget no longer works in the majority of browsers.

All Our Ideas uses these cookies to track voting sessions. In order to support the widget in an iframe, we'd need to create an alternate mechanism for tracking these sessions without cookies. The best option that should have continued browser support would be to replicate the job of these cookies with session data that gets included with any form submission (vote, skip, or submission of new idea) within the widget. In other words, instead of setting the cookies in the header of responses, these session identifiers would be hidden inputs in these HTML forms.

**Comment by msalganik** [comment]
We have decided not to support the widget going forward (https://blog.allourideas.org/post/639313105195876352/wiki-survey-widgets-are-no-longer-supported) so I'm closing this issue.
