### ISSUE TITLE
remove wiki survey embed code from wiki survey settings

### ISSUE THREAD

**Issue by msalganik** [allourideas/allourideas.org#83]
Because we no longer support the wiki survey embed process (https://blog.allourideas.org/post/639313105195876352/wiki-survey-widgets-are-no-longer-supported), we should remove it from the admin control panel (www.allourideas.org/[your_url]/admin).  In other words, the wiki survey embed code should no longer appear on this page.

Here's part of the screenshot of where it appears.

<img width="200" alt="Screen Shot 2021-01-03 at 2 33 05 PM" src="https://user-images.githubusercontent.com/142116/103487085-b7602580-4dd0-11eb-9684-1d8e0c5a32ef.png">

**Comment by lukebaker** [comment]
This is all set, @msalganik

**Comment by msalganik** [comment]
Great.  Thanks @lukebaker
